#!/usr/bin/env -vS -i PATH="${PATH}" LANG="${LANG}" TERM='xterm-256color' DISPLAY="${DISPLAY}" HOME="${HOME}" bash --noprofile --norc

cp ./qterminal.ini ~/.config/foo_qterminal.conf
qterminal -p foo_qterminal -e 'less -R --shift 5 -- ./less.txt'
