#!/bin/bash
#
#unset RUST_BACKTRACE
#workaround issue: 29293 https://github.com/rust-lang/rust/issues/29293
echo "RUST_BACKTRACE=$RUST_BACKTRACE"
echo "RUST_LOG=$RUST_LOG"
#time cargo build -v -- "$@"
time cargo run -v -- "$@"
#FIXME: have RUST_LOG not affect cargo during cargo run!


