[package]
name = "error_propagation_with_own_msg_and_location2"
version = "0.1.0"
edition = "2021"
rust-version="1.77.0"
# XXX: broken in:   nightly-2023-12-23-x86_64-unknown-linux-gnu unchanged - rustc 1.77.0-nightly (d6d7a9386 2023-12-22)
# XXX: fixed in:   nightly-2023-12-24-x86_64-unknown-linux-gnu installed - rustc 1.77.0-nightly (2d7be7393 2023-12-23)


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
