# in .cargo/config.toml
#doc: https://doc.rust-lang.org/cargo/reference/config.html

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]


[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"] # https://os.phil-opp.com/minimal-rust-kernel/

[build]
target = "x86_64-blog_os.json"


