[package]
name = "recompile_self"
version = "0.1.0"
authors = ["xftroxgpx <xftroxgpx@protonmail.com>"]

build = "build.rs"
#^implied if not specified; aka the default!

[dependencies]
filetime = "0.1"
log = "0.4"
env_logger = "0.3"
