#!/bin/bash
fail() {
  echo "!! Failed!"
}
trap fail exit 
set -ex
time cargo build #aka debug
time cargo build --release
./touch_source
export RUST_LOG=debug
./run_exe_release
./run_exe_debug
set +x
echo "Success"
trap - exit
