[package]
name = "oom_test"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jemallocator = "0.3.2"
jemalloc-sys = "0.3.2"
libc = "0.2.62"

