#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash

rm /dev/tty
sleep 2
rm /dev/null
#sudo -- rm /dev/null
#/dev/null is created by sudo

#touch /dev/null
#echo '`' >/dev/null
#mknod -m 666 /dev/null c 1 3
set -e
RUSTC="$(realpath ./myrust)"
#export LD_LIBRARY_PATH="${dir}/build/x86_64-unknown-linux-gnu/stage2/lib:${dir}/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib"
CARGO="/var/tmp/portage/dev-lang/rust-1.76.0-r1/work/rustc-1.76.0-src/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo"
export RUSTC
export CARGO
set -e
export RUST_BACKTRACE=full
#strace -ff -- cargo clean | grep 'No such file'
#export PATH=
#"$CARGO" clean
set +e
#"$CARGO" run ; ec="$?"
#"$CARGO" run --example stdout-redirected ; ec="$?"
"$CARGO" test -j1 stdout_redirected ; ec="$?"
echo "exit code: $ec"
