#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash


#defer deletion else 'sudo'\* already made a new 0 byte file /dev/null
#\* or something else like executing any benign ./script from 'mc' aka midnight commander, yep this is it!!! even empty script as long as u press Enter on it
(sleep 1 ; rm /dev/null ) &
sudo -u user -- ./gmy
