#!/usr/bin/env bash

#defer deletion else 'sudo'\* already made a new 0 byte file /dev/null
#\* or something else like executing any benign ./script from 'mc' aka midnight commander, yep this is it!!! even empty script as long as u press Enter on it
(sleep 1 ; rm /dev/null ) &
sudo -u user -- ./gmy
