#!/bin/bash
#
#unset RUST_BACKTRACE
#workaround issue: 29293 https://github.com/rust-lang/rust/issues/29293
echo "RUST_BACKTRACE=$RUST_BACKTRACE"
echo "RUST_LOG=$RUST_LOG"
if test -x ./prereq; then
  ./prereq
fi

time cargo rustc --verbose --release -- -C incremental=incremental.compilation.storage.dir -C lto=off -Z borrowck=mir -v "$@"
#time cargo rustc --verbose --release -- -C incremental -C lto=off -Z borrowck=mir -v "$@"
#error: codegen option `incremental` requires a string (C incremental=<value>)


#error: can't perform LTO when compiling incrementally

#the extra -C ones are optional and added for future reference only! ie. grepping for "cargo rustc" because I forgot how to add options for it


