#!/bin/bash

srcfile="show_all_opened.py"

if test "$1" == "edit"; then
  vim -- "$srcfile"
  exit "$?"
fi

source "/swcode/swcode.bash"
rerunasroot "$@"


#release mode, equivalent to passing arg -OO to python or pypy3
export PYTHONOPTIMIZE=2
#    If this is set to a non-empty string it is equivalent to specifying the -O option. If set to an integer, it is equivalent to specifying -O multiple times.

#debug mode(overrides the above!):
export -n PYTHONOPTIMIZE
unset PYTHONOPTIMIZE
#Note: change in the above doesn't require the removal of the dir: ./.mypy_cache/

if test -z "$PYTHONOPTIMIZE"; then
  echo "Debug mode (asserts enabled!)"
else
  echo "Release/optimized mode(asserts disabled)"
fi

#time mypy --python-executable=/usr/bin/python3 --strict /dev/null "./$srcfile" && 
  /usr/bin/python3 -bb "./$srcfile"

