language: rust
sudo: false

cache: cargo

os:
- linux
- osx

rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
  - rust: nightly

before_script:
    - pip2 install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$HOME/Library/Python/2.7/bin:$PATH

script:
- travis-cargo build &&
  travis-cargo test &&
  travis-cargo test -- --no-default-features &&
  travis-cargo --only stable doc -- --all-features

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo --only stable doc-upload; fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
