#!/bin/bash

set -e
rm a.out || true
gcc -fuse-ld=gold -Wl,--gc-sections main.c -Wa,--generate-missing-build-notes=yes
rm a.out || true
gcc -fuse-ld=gold -Wa,--generate-missing-build-notes=yes -Wl,--gc-sections main.c
# not an issue with the following ArchLinux's binutils ld.gold:
#GNU gold (GNU Binutils 2.31.1) 1.16
#GNU gold (GNU Binutils 2.32) 1.16
#
#even though 2.32 doesn't use[1] the patch mentioned here[2]
#[1] https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/binutils&id=8e3f40011ddc933f016d6f126c3b3cb24e711c28
#[2] https://bugzilla.redhat.com/show_bug.cgi?id=1600431#c6

echo 'All good'
