#src: https://docs.travis-ci.com/user/languages/rust/

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: stable

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
