#src: https://docs.travis-ci.com/user/languages/rust/
#XXX: note travis for this repo is currently disabled!

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true

script: helper_scripts/travis_script.sh
