#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash


find . -name target -type d -print0 | xargs -P0 -0 --no-run-if-empty --verbose -- rm --one-file-system --preserve-root=all --recursive --
