#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash


source "/swcode/swcode.bash"

rerunasroot "$@"

set -e
source vars.sh
set +e

chmod -v -- o+rx,g+rx "${dir}/"{../../,../}
