#!/usr/bin/env bash

#cd /tmp || cd / #XXX to avoid this spam: shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

source "/swcode/swcode.bash"

rerunasroot "$@"

set -e
source vars.sh
set +e

while true; do

echo "Monitoring current (re)compilation...C-c is your friend."

libtests=0
charsperline=0
prev=""
while test "$libtests" -ne "6"; do
  libtests="$(find "${dir}/build/" -iname \*libtest\* 2>/dev/null |grep stage1|wc -l)"
  sleep 1 #sometimes it misses the kill because it had nothing new/modded to compile, so this must be low
  now="$libtests"
  if test "$prev" != "$now"; then
    prev="$now"
    echo -n "$libtests"
  fi
  ((charsperline++))
  if (( charsperline > 200 )); then
    echo #new line, to ease the load on terminal!
    charsperline=0
  fi
done
echo

#chmod o+rx,g+rx /var/tmp/portage/dev-lang/rust-1.75.0-r1{,/work}
#chmod o+rx,g+rx /var/tmp/portage/dev-lang/rust-1.76.0-r1/work/rustc-1.76.0-src/{../../,../}
chmod o+rx,g+rx "${dir}/"{../../,../}
sleep 5 #just in case it kills it too soon!
pkill --echo -u portage -- 'rustc'

echo "Waiting for next recompilation...C-c if not."
charsperline=0
prev=""
while test "$libtests" -eq "6"; do
  libtests="$(find "${dir}/build/" -iname \*libtest\* 2>/dev/null |grep stage1|wc -l)"
  sleep 1
  now="$libtests"
  if test "$prev" != "$now"; then
    prev="$now"
    echo -n "$libtests"
  fi
  ((charsperline++))
  if (( charsperline > 200 )); then
    echo #new line, to ease the load on terminal!
    charsperline=0
  fi
done
echo

done
