#!/usr/bin/env bash

source "/swcode/swcode.bash"

rerunasroot "$@"
set -e

ebuild `equery w rust` clean prepare
#dir="/var/tmp/portage/dev-lang/rust-1.75.0-r1/work/rustc-1.75.0-src/"
#dir="/var/tmp/portage/dev-lang/rust-1.76.0-r1/work/rustc-1.76.0-src/"
source vars.sh
cd "$dir"
#patch -p8 -i /quilt_patches/cargo_test-threads_loses_output.patch
#patch -p8 -i /quilt_patches/cargo_test-threads_loses_output2.patch
patch -p8 -i /quilt_patches/cargo_test-threads_loses_output4.patch
echo "`tput setab 2`$dir`tput sgr0`"
