#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash


source "/swcode/swcode.bash"

rerunasroot "$@"

source vars.sh
#rm -- "/var/tmp/portage/dev-lang/rust-1.76.0-r1/.compiled"
rm -- "${dir}/../../.compiled"
time ebuild `equery w rust` compile > /tmp/compile.output || less /tmp/compile.output
