[package]
name = "unified_bin_and_lib_manuallybuiltlib"
version = "0.1.0"
edition = "2021"
exclude = ["/target*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#crate-type = ["cdylib"]
#link = "dylib" #warning: unused manifest key: lib.link
#path = "src/lib2.rs"
#XXX: had to rename it from lib.rs to lib2.rs else 'use lib;' in main.rs would complain: 
#warning: found module declaration for lib.rs
# --> /home/user/sandbox/rust/05_sandbox/dynamic_lib/unified_bin_and_lib/src/main.rs:1:1
#  |
#1 | mod lib;
#  | ^^^^^^^^
#  |
#  = note: lib.rs is the root of this crate's library target
#  = help: to refer to it from other targets, use the library's name as the path
#  = note: `#[warn(special_module_name)]` on by default


[profile.dev]
opt-level = 0
incremental=false
#rpath=true #no effect
## ... other dev profile settings
#link = "dylib" # Only if dynamic_linking is enabled
#
[profile.release]
#rpath=true
## ... other release profile settings
#link = "dylib" # Only if dynamic_linking is enabled


#[build] #unused key
#rustc-link-lib = ["unified_bin_and_lib"]
#script = "build.rs"

[dependencies]
#unified_bin_and_lib = { path="./" } #cyclic dep
#[build-dependencies]
#cargo_toml = "0.19.2"

