#!/usr/bin/env bash
export RUST_BACKTRACE=1
cargo clean
#FIXME: needs double build to finally compile it O_o
cargo build -vv
cargo build -vv

cargo run -vv
ec="$?"
pushd target/debug
#FIXME: need to set lib path, make it not necessary!
LD_LIBRARY_PATH=./ ./unified_bin_and_lib
ec2="$?"
./unified_bin_and_lib
ec3="$?"
popd
echo "exit code: $ec $ec2 $ec3"
