#!/bin/bash

# try-program to show lhs,op,rhs see: https://github.com/rust-lang/rust/issues/43731

time "${HOME}/build/2nonpkgs/rust.stuff/rust/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" --edition=2018 -C debuginfo=2 "$@" ./src/main.rs -v && RUST_LOG=trace RUST_BACKTRACE=0 ./main
