#!/bin/bash


#XXX: that target cpu "intel" is bad arg, but just testing! `'intel' is not a recognized processor for this target (ignoring processor)`
#do this to see list of processors: rustc -C target-cpu=help|less   but what u want is probably 'native' instead of the default 'x86-64', well unless planning to dist the binary, I guess.

#time cargo rustc --verbose --release -- -v "$@"
export RUSTFLAGS="$RUSTFLAGS -Z treat-err-as-bug=3000" #this works, it's appended!
time cargo rustc --verbose --release -- -Z treat-err-as-bug=2000 -C target-cpu=intel -v "$@" #doesn't work, the ~/.cargo/config is appended last!
#fail:
#FIXME: How can I override rustc args specified in ~/.cargo/config from the command line? I tried: time cargo rustc --verbose --release -- -Z treat-err-as-bug=2000 -C target-cpu=intel -v "$@"  but got: note: compiler flags: -Z treat-err-as-bug=2000 -Z treat-err-as-bug=1 -C opt-level=3 -C lto -C codegen-units=1 -C target-cpu=intel -C debug-assertions=on -C target-cpu=native --crate-type bin  Had the following in ~/.cargo/config: [target.'cfg(any(windows, unix))'] rustflags = ["-C", "target-cpu=native" , "-Z", "treat-err-as-bug=1" ]
