[package]
name = "how_much_stack_is_left"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stacker="0.1.15"

[profile.dev]
#lto='fat' #for https://github.com/japaric/cargo-call-stack?tab=readme-ov-file
#^ changes the current stack calculations that I've done manually in the program, like depth is <=54 not 58
