#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash
#rust-gdb /tmp/multipath_backoff5 "/coredumps/$(ls -rat /coredumps/|tail -n1)"
rust-gdb /tmp/multipath_backoff5 "$(find /coredumps/ | tail -n1)"
