#!/bin/bash

vdifile="/tmp/moo.vdi"
tempddfile="/tmp/shie.dd"
set -xev
cargo build
cargo bootimage
dd if="/dev/zero" of="$tempddfile" count=1 bs=1M
dd if=./target/x86_64-blog_os/debug/bootimage-blog_os.bin of="$tempddfile" conv=notrunc
set +e
if test -f "$vdifile"; then
  set -e
  rm -- "$vdifile"
else
  set -e
fi
VBoxManage convertdd "$tempddfile" "$vdifile" --format VDI
#this moo.vdi is already linked as IDE HDD in virtualbox, but new contents invalidates it!
#VBoxManage modifyvm "blog_os" --hda "/tmp/moo.vdi"

#src: https://serverfault.com/a/997311
vmname="blog_os"
#release from vm
VBoxManage storageattach "$vmname" --storagectl "IDE" --device 0 --port 0 --type hdd --medium none
#remove from virtualbox
VBoxManage closemedium disk "$vdifile"
#add to vm
VBoxManage storageattach "$vmname" \
                         --storagectl "IDE" \
                         --device 0 \
                         --port 0 \
                         --type hdd \
                         --medium "$vdifile"

