[package]
name = "l_19_15"
version = "0.1.0"
authors = [ "CEhowNSaboutORsynergyED" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-rational = "0.2"
num-bigint = "0.2"

