#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash


export RUST_BACKTRACE=1
export RUSTFLAGS="-Z debug-macros -Z macro-backtrace -Z trace-macros"
cargo run ; ec="$?"
if test "0" == "$ec"; then
  cargo expand
fi
echo "exit code: $ec"
#sleep 2
