#!/bin/bash

set +e
#cargo clean -v -p "${PWD##*/}"
#^ project name might be different than current dir's name!
cargo clean -vv
#^ clean only the exe  aka -p projectnamehere
# to clean all(the deps too, eg. when using clippy, its deps which are kinda costly to rebuild then just don't use -p ...)
find . -name target -type d -print0 | xargs -0 --no-run-if-empty --exit -P0 -- rm -vr --
#^ 'rls' ran by 'ale' (in vim) creates a ./target/ in each project dir!
echo 'Done'
