#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash
#g++ -fPIC -std=c++11 -Wall -o myprogram main.cpp $(pkg-config --cflags --libs Qt5Core)
#g++ -fPIC -std=c++11 -Wall -o myprogram main.cpp -I/usr/include/qt -I/usr/include/qt/QtCore -lQt6Core $(pkg-config --cflags --libs Qt6Core)
#g++ -fPIC -std=c++11 -Wall -o myprogram main.cpp $(pkg-config --cflags --libs Qt6Core)
g++ -fPIC -Wall -o myprogram main.cpp $(pkg-config --cflags --libs Qt6Core)
