#!/usr/bin/env bash
#g++ -fPIC -std=c++11 -Wall -o myprogram main.cpp $(pkg-config --cflags --libs Qt5Core)
#g++ -fPIC -std=c++11 -Wall -o myprogram main.cpp -I/usr/include/qt -I/usr/include/qt/QtCore -lQt6Core $(pkg-config --cflags --libs Qt6Core)
#g++ -fPIC -std=c++11 -Wall -o myprogram main.cpp $(pkg-config --cflags --libs Qt6Core)
g++ -fPIC -Wall -o myprogram main.cpp $(pkg-config --cflags --libs Qt6Core)
