#!/bin/bash

projectname=`cat Cargo.toml|perl -n -e'/name = "(.+)"/ && print $1'`
#cargo clean -v -p "${PWD##*/}"
#^ project name might be different than current dir's name!
cargo clean -v -p "${projectname}"
#^ clean only the exe  aka -p projectnamehere
# to clean all(the deps too, eg. when using clippy, its deps which are kinda costly to rebuild then just don't use -p ...)

