#!/usr/bin/env bash
export RUST_BACKTRACE=1
cargo clean
trap 'echo -e "\nCtrl-C pressed, but NOT also exiting script!"' SIGINT
cargo run ; ec="$?"
echo "exit code: $ec"
#128+2 where 2 is SIGINT (see $ kill -l )
if test "$ec" == 130; then
  #ie. pressed C-c due to deadlock, then debug it
  echo "$(tput setab 1)Press 'r' inside gdb to run it, and C-c again when deadlocked, then 'bt' to see stacktrace!$(tput sgr0)"
  rust-gdb target/debug/deadlock_on_cleanup
fi
