[package]
name = "error_propagation_with_own_msg_and_location"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#build = "build.rs"
#XXX: ^ that's not needed as long as that file exists, hmm!

[dependencies]
