#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash

set -e
export RUST_BACKTRACE=1
#cargo clean
cargo build
#set -vx
set +e
cargo run
cargo run -- --help
cargo run -- -u91
#cargo run -- -u=91 #no good
cargo run -- -u
cargo run -- -u 83
cargo run -- -U 12
cargo run -- -U21
#cargo run -- -U-21 #no negatives
#cargo run -- -U=21 #no good
#cargo run -- --unified 34 #no good! 34 is a free arg because it's optional!
cargo run -- --unified=43
#cargo run -- --debug -d
