[package]
name = "lazystatique_infinite_recursion"
version = "0.1.0"
authors = ["xftroxgpx <xftroxgpx@protonmail.com>", "Timofey Martynov feymartynov" ]
edition = "2018"

[dependencies]
lazy_static='1.2.0'
