#!/bin/bash
#
#unset RUST_BACKTRACE
#workaround issue: 29293 https://github.com/rust-lang/rust/issues/29293
echo "RUST_BACKTRACE=$RUST_BACKTRACE"
echo "RUST_LOG=$RUST_LOG"
#time cargo run -v --no-default-features --features "rand","uuid" -- "$@"
#thanks sebk on irc for --no-default-features
time cargo run -v --features "uuid","rand" -- "$@"
# ^ should fail if default feature is rand ! because this one also adds uuid and both can't be used!


