#!/bin/bash
#^ syntax highlighting

echo execute ./go from vim by typing:   :!./go
#unset RUST_BACKTRACE #workaround issue: 29293 https://github.com/rust-lang/rust/issues/29293
#or else it will hang on each file write (when rust.vim and syntactic!)

fil="./src/main.rs"
if ! test -e "$fil"; then
  fil="./src/lib.rs"
fi
#time vim -- "$fil" && rustfmt -- "$fil"
time "${EDITOR:-nvim}" -- "$fil" && cargo-fmt && cargo check
#because rustfmt -- "$fil" will just error[E0670]: `async fn` is not permitted in the 2015 edition
