#!/bin/bash
git diff --no-index --word-diff=plain --word-diff-regex='\s*[a-zA-Z0-9]+\s*' --color=always -- ./{1,3}.log
git diff --no-index --word-diff=plain --word-diff-regex='\s+[a-zA-Z0-9]+\s+' --color=always -- ./{1,3}.log #this works only for this specific case, can't use it in general tho!

#git diff --no-index --word-diff=plain --word-diff-regex='\s+[a-zA-Z0-9]+\s+' --color=always -- ./{1,3}.log
#git diff --no-index --word-diff=plain --word-diff-regex='(^[^a-zA-Z0-9]+[^\s]+)?[a-zA-Z0-9]+([^[\s]+[^a-zA-Z0-9]+$)?' --color=always -- ./{1,3}.log
