#!/bin/bash
git wdiff  --no-index -- {1,3}.log | cat
git wdiff2 --no-index -- {1,3}.log | cat
git wdiff  --no-index -- {1,2}.log | cat
git wdiff2 --no-index -- {1,2}.log | cat
#this only works if in your ~/.gitconfig or if you don't already have one, then in /etc/gitconfig
#you have these 2 lines:
#[alias]
#  wdiff = diff --word-diff=plain --word-diff-regex='[[:alnum:]]+|[^[:alnum:][:space:]]|[[:space:]]' --color=always
#  #and
#  wdiff2 = diff --word-diff=plain --word-diff-regex=. --color=always
