#!/bin/bash
git wdiff  --no-index -- {1,3}.log
git wdiff2 --no-index -- {1,3}.log
#this only works if in your ~/.gitconfig or if you don't already have one, then in /etc/gitconfig
#you have these 2 lines:
#[alias]
#  wdiff = diff --word-diff=plain --word-diff-regex='[[:space:]]*[[:alnum:]]+[[:space:]]*' --color=always
#  #or
#  wdiff1 = diff --word-diff=plain --word-diff-regex='\\s*[a-zA-Z0-9]+\\s*' --color=always
#  #and
#  wdiff2 = diff --word-diff=plain --word-diff-regex=. --color=always
