#!/bin/bash
files=( {4,5}.log )
set -x
unset PAGER #no effect, have to use "| cat"
git diff --no-index --word-diff=plain --word-diff-regex='\s*[a-zA-Z0-9]+\s*|\s*[#]+\s*' --color=always -- "${files[@]}" | cat
git diff --no-index --word-diff=plain --word-diff-regex='\s*[a-zA-Z0-9]+\s*|\s*[^[:alnum:]]\s*' --color=always -- "${files[@]}" | cat
git diff --no-index --word-diff=plain --word-diff-regex='[[:space:]]*[[:alnum:]]+[[:space:]]*' --color=always -- "${files[@]}" | cat
git diff --no-index --word-diff=plain --word-diff-regex='\s+[a-zA-Z0-9]+\s+' --color=always -- "${files[@]}" | cat
#this works only for this specific case, can't use it in general tho!

git diff --no-index --word-diff=plain --word-diff-regex='[[:alnum:]]+|[^[:alnum:][:space:]]+' --color=always -- "${files[@]}" | cat
#^ presumably(chatgpt guessed) this is the default --word-diff-regex= that git uses! aka broken see ./go_fail

#git diff --no-index --word-diff=plain --word-diff-regex='(^[^a-zA-Z0-9]+[^\s]+)?[a-zA-Z0-9]+([^[\s]+[^a-zA-Z0-9]+$)?' --color=always -- "${files[@]}"

git diff --no-index --word-diff=plain --word-diff-regex='[^[:alnum:]]*[[:alnum:]]+[^[:alnum:]]*' --color=always -- "${files[@]}" | cat

git diff --no-index --word-diff=plain --word-diff-regex='.' --color=always -- "${files[@]}" | cat


git diff --no-index --word-diff=plain --word-diff-regex='[[:alnum:]]+|[^[:alnum:][:space:]]|[[:space:]]' --color=always --  {1,2}.log | cat
git diff --no-index --word-diff=plain --word-diff-regex='[[:alnum:]]+|[^[:alnum:][:space:]]|[[:space:]]' --color=always --  {1,3}.log | cat
git diff --no-index --word-diff=plain --word-diff-regex='[[:alnum:]]+|[^[:alnum:][:space:]]|[[:space:]]' --color=always --  {4,5}.log | cat
git diff --no-index --word-diff=plain --word-diff-regex='[[:alnum:]]+|[^[:alnum:][:space:]]|[[:space:]]' --color=always --  {6,7}.log | cat
