#!/bin/bash

#tested to fail as below with: ArchLinux's rsync-3.1.2-8-x86_64.pkg.tar.xz
#untested to fail as below with: ArchLinux's rsync-3.1.3pre1-1-x86_64.pkg.tar.xz
#tested to fail as below with: ArchLinux's rsync-3.1.3-1-x86_64.pkg.tar.xz
#tested to fail as below with: rsync-git-3.1.3.r3.geec6ab76-1-x86_64.pkg.tar
#tested to fail as below with: rsync-git-3.1.3.r4.g1eb7a706-1-x86_64.pkg.tar

if test -n "$DEBUG"; then
  dbg="--debug=FILTER1"
else
  dbg=""
fi

if test "$1" == "clean"; then
  rm -vrf destdir sourcedir s d
  exit 0
fi

echo '!! test 0: should be good' >&2
mkdir -p destdir
mkdir -p sourcedir/a
touch sourcedir/file1
touch sourcedir/a/file2
echo 'sourcedir' >/tmp/filesfrom.lst.tmp
echo 'sourcedir/a/file2' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/

echo '!! test 1: should be good' >&2
mkdir -p destdir
mkdir -p sourcedir/a
touch sourcedir/file1
touch sourcedir/a/file2
echo 'sourcedir' >/tmp/filesfrom.lst.tmp
echo 'sourcedir/a/' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/

echo '!! test 2: should be good' >&2
mkdir -p destdir
mkdir -p sourcedir/a
touch sourcedir/file1
touch sourcedir/a/file2
echo 'sourcedir' >/tmp/filesfrom.lst.tmp
echo 'sourcedir/a' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/

echo '!! test 3: should be good' >&2
mkdir -p destdir
mkdir -p sourcedir/a
touch sourcedir/file1
touch sourcedir/a/file2
echo 'sourcedir' >/tmp/filesfrom.lst.tmp
echo '/sourcedir/a' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/

echo '!! test 4: should be good' >&2
mkdir -p destdir
mkdir -p sourcedir/a
touch sourcedir/file1
touch sourcedir/a/file2
echo 'sourcedir' >/tmp/filesfrom.lst.tmp
echo '/sourcedir/a/' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/

if test -r destdir/sourcedir/a/file2; then
  echo '(one or more of the)previous test(s) failed'
else
  echo 'so far so good' #or, more accurately, the last test was good (due to --delete-excluded)
fi

echo '!! test 5: should fail to exclude due to adjacent slashes in filter' >&2

mkdir -p destdir
mkdir -p sourcedir/a
touch sourcedir/file1
touch sourcedir/a/file2
echo 'sourcedir' >/tmp/filesfrom.lst.tmp
echo 'sourcedir//a/' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/
if test -r destdir/sourcedir/a/file2; then
  echo 'test 5 failed'
else
  echo 'test 5 succeeded, you fixed it!'
fi

echo '!! test 6: should fail to exclude due to adjacent slashes in filter' >&2

mkdir -p destdir
mkdir -p sourcedir/a
touch sourcedir/file1
touch sourcedir/a/file2
echo 'sourcedir' >/tmp/filesfrom.lst.tmp
echo '//sourcedir/a' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/
if test -r destdir/sourcedir/a/file2; then
  echo 'test 6 failed'
else
  echo 'test 6 succeeded, you fixed it!'
fi

echo '!! test 7: should fail to exclude due to adjacent slashes in filter' >&2

mkdir -p destdir
mkdir -p sourcedir/a
touch sourcedir/file1
touch sourcedir/a/file2
echo 'sourcedir' >/tmp/filesfrom.lst.tmp
echo '//sourcedir//a//' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/
if test -r destdir/sourcedir/a/file2; then
  echo 'test 7 failed'
else
  echo 'test 7 succeeded, you fixed it!'
fi

echo '!! test 8: should fail to exclude due to adjacent slashes in filter' >&2

mkdir -p destdir
mkdir -p sourcedir/a
touch sourcedir/file1
touch sourcedir/a/file2
echo 'sourcedir' >/tmp/filesfrom.lst.tmp
echo '//sourcedir//a//file2' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/
if test -r destdir/sourcedir/a/file2; then
  echo 'test 8 failed'
else
  echo 'test 8 succeeded, you fixed it!'
fi

echo '!! test 9: should fail to exclude due to adjacent slashes in filter' >&2

mkdir -p destdir
mkdir -p sourcedir/a
touch sourcedir/file1
touch sourcedir/a/file2
echo 'sourcedir' >/tmp/filesfrom.lst.tmp
echo '//sourcedir//a//////file2' >/tmp/excluded.lst.tmp
#echo '/sourcedir/a/file2' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/
if test -r destdir/sourcedir/a/file2; then
  echo 'test 9 failed'
else
  echo 'test 9 succeeded, you fixed it!'
fi

echo '!! test 10: should work' >&2
mkdir -p d
mkdir -p s/a
touch s/file1
touch s/a/file2
echo 's' >/tmp/filesfrom.lst.tmp
echo 's' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/
if test -r destdir/sourcedir/a/file2; then
  echo 'test 10 failed'
else
  echo 'test 10 succeeded'
fi

echo '!! test 11: should work' >&2
mkdir -p d
mkdir -p s/a
touch s/file1
touch s/a/file2
echo 's' >/tmp/filesfrom.lst.tmp
echo 's/' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/
if test -r destdir/sourcedir/a/file2; then
  echo 'test 11 failed'
else
  echo 'test 11 succeeded'
fi

echo '!! test 12: should work' >&2
mkdir -p d
mkdir -p s/a
touch s/file1
touch s/a/file2
echo 's' >/tmp/filesfrom.lst.tmp
echo '/' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/
if test -r destdir/sourcedir/a/file2; then
  echo 'test 12 failed'
else
  echo 'test 12 succeeded'
fi

echo '!! test 13: should fail to exclude due to adjacent slashes in filter' >&2
mkdir -p d
mkdir -p s/a
touch s/file1
touch s/a/file2
echo 's' >/tmp/filesfrom.lst.tmp
echo '//' >/tmp/excluded.lst.tmp
rsync --recursive --perms --delay-updates --files-from=/tmp/filesfrom.lst.tmp --exclude-from=/tmp/excluded.lst.tmp --delete-excluded $dbg -- ./ ./destdir/
if test -r destdir/sourcedir/a/file2; then
  echo 'test 13 failed'
else
  echo 'test 13 succeeded, you fixed it!'
fi
#rsync --version
#pacman -Qs rsync
