#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash

diff -up <(cat erm.log) <(CLICOLOR_FORCE= cmake -P ermfixed.cmake 2>&1)
if test "$?" == 0; then
  echo "success, outputs are the same"
else
  echo "failed, different outputs"
fi

