[package]
name = "workout"
version = "0.1.0"
authors = [ "CExftNSroxORgpxED" ]

[dependencies]
#cursive = "0.2"
cursive = { git = "https://github.com/gyscos/Cursive" }
#cursive = { path = "/home/user/build/2nonpkgs/rust.stuff/Cursive" }

