#!/bin/bash
#
#note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
export CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true
export RUST_BACKTRACE=1
#unset RUST_BACKTRACE
#workaround issue: 29293 https://github.com/rust-lang/rust/issues/29293
echo "RUST_BACKTRACE=$RUST_BACKTRACE"
echo "RUST_LOG=$RUST_LOG"
if test -x ./prereq; then
  ./prereq
fi
if test "$1" != "noclippy"; then
  set -e
  time cargo clippy -- -A clippy::write_with_newline -A clippy::needless_borrows_for_generic_args -A clippy::needless_borrowed_reference
else
  set -e
fi
time cargo run -v -- "$@"


