#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash


set -vex

git clone https://github.com/lukaslueg/built.git
pushd built
git checkout a10808ac73c63568e6455aa7eef1945960a89bcd
patch -p1 -i ../a.patch
popd
set +vex
echo "All done"
