#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash


cp workspace.rs.original workspace.rs
./patch -p0 -i ./wrong_place.patch
if diff -qup -- workspace.rs.HUNK_IN_WRONG_PLACE workspace.rs; then
  echo "Still failed"
  exit 1
fi
