#!/bin/bash
#^ syntax highlighting

#unset RUST_BACKTRACE #workaround issue: 29293 https://github.com/rust-lang/rust/issues/29293
#or else it will hang on each file write (when rust.vim and syntactic!)

time vim ./src/client.rs
