[package]
name = "proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"

#[build]
## Specify the path to the C compiler (e.g., GCC or Clang)
#cc = "/usr/bin/cc"
