[package]
name = "two"
version = "0.1.0"
authors = ["offline <offline@Z575>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpi = { git = "https://github.com/bsteinb/rsmpi", rev = "f9aec8b8d82" }
