[package]
name = "own_made_screenlocker_triggerer"
version = "0.1.0"
edition = "2021"

# Exclude the specified subdirectory
exclude = ["home_dir", "g", "e"]

[profile.dev]
opt-level=0
debug=2
debug-assertions=true
overflow-checks = true
lto = false
panic= "unwind"

[profile.release]
opt-level=3
debug=2
debug-assertions=true
overflow-checks = true
lto = "thin"
panic= "unwind"


[dependencies]
x11 ="2.20.0"
