[package]
name = "pthread_atfork_try2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]

[profile.release]
lto=true
codegen-units=1

[dependencies]
libc = "0.2"
#libc = { path = "../libc" }

