#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash

echo "attempts to compile for windows, on gentoo, will fail to link!"
export RUST_BACKTRACE=1
cargo clean
#cargo run --target=x86_64-pc-windows-msvc
#cargo run --target=x86_64-w64-mingw32
#^ doesn't exist in: rustc --print target-list

#cargo run --target=x86_64-pc-windows-gnu
#^ I don't have something on Gentoo
#error[E0463]: can't find crate for `core`
#  |
#  = note: the `x86_64-pc-windows-gnu` target may not be installed
#  = help: consider downloading the target with `rustup target add x86_64-pc-windows-gnu`
#  = help: consider building the standard library from source with `cargo build -Zbuild-std`

#export RUSTFLAGS="-Clink-self-contained=no" #no effect on the missing rsbegin.o and rsend.o
#-Clink-self-contained=no is from: https://github.com/rust-lang/rust/issues/117548#issuecomment-1792837617
cargo run --target=x86_64-pc-windows-gnu -Zbuild-std
#^ fails linking like this:
#  = note: /usr/libexec/gcc/x86_64-w64-mingw32/ld: cannot find rsbegin.o: No such file or directory
#          /usr/libexec/gcc/x86_64-w64-mingw32/ld: cannot find -l:libpthread.a: No such file or directory
#          /usr/libexec/gcc/x86_64-w64-mingw32/ld: cannot find rsend.o: No such file or directory
#          collect2: error: ld returned 1 exit status
# on nixos the rsbegin.o and rsend.o aren't an issue, because I used rustup!
echo "exit code: $?"
sleep 2
