#!/usr/bin/env bash

echo "attempts to compile for windows, on nixos"
export RUST_BACKTRACE=1
cargo clean
#cargo run --target=x86_64-pc-windows-msvc
#cargo run --target=x86_64-w64-mingw32
#^ doesn't exist in: rustc --print target-list

#cargo run --target=x86_64-pc-windows-gnu
#^ I don't have something on Gentoo
#error[E0463]: can't find crate for `core`
#  |
#  = note: the `x86_64-pc-windows-gnu` target may not be installed
#  = help: consider downloading the target with `rustup target add x86_64-pc-windows-gnu`
#  = help: consider building the standard library from source with `cargo build -Zbuild-std`

nix-shell cross_compile.nix --command "cargo build -vv --jobs=1"
#nix-shell default.nix --command "cargo build -vv --jobs=1"
# --target=x86_64-pc-windows-gnu"
#--config target.x86_64-pc-windows-gnu.linker=\\\"`realpath ./linker.sh`\\\" "
#|& /run/current-system/sw/bin/grep -vF \"dangerous relocation: R_AMD64_IMAGEBASE with __ImageBase undefined\" "
#; \"cc\" --version"
#; cc --version"
#export |grep -F PATH"
#echo \"!!\$CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER\" "
#|& grep -F 'ucrt' "
#; export|grep -i RUST"
#&& cargo run --target=x86_64-pc-windows-gnu && cargo test --target=x86_64-pc-windows-gnu"
#-Zbuild-std
#^ fails linking like this:
#  = note: /usr/libexec/gcc/x86_64-w64-mingw32/ld: cannot find rsbegin.o: No such file or directory
#          /usr/libexec/gcc/x86_64-w64-mingw32/ld: cannot find -l:libpthread.a: No such file or directory
#          /usr/libexec/gcc/x86_64-w64-mingw32/ld: cannot find rsend.o: No such file or directory
#          collect2: error: ld returned 1 exit status
echo "exit code: $?"
#sleep 2
