#!/bin/bash
#src: https://stackoverflow.com/a/20018118

#cat >/dev/null <<EOF
cleanup() {
  rm -v -- /tmp/mumufifo
  trap - EXIT SIGINT
}
trap cleanup EXIT SIGINT
mkfifo /tmp/mumufifo
#coproc { tail -f "/tmp/ninja.chromium.stderrandout"; } > /tmp/mumu
#jobpid="$COPROC_PID" #not tail's pid, so I have to use & instead
grep --color=always -E "^ninja: build stopped:" </tmp/mumufifo &  #thanks glacial on #bash, freenode irc
tail -f "/tmp/ninja.chromium.stderrandout" > /tmp/mumufifo &
jobpid="$!" #still not tail's pid when redit to fifo, not when redir to file or null
echo "jobpid=$jobpid parent:`pgrep -P "$jobpid"`"
ps "$jobpid"
#EOF

wait
#XXX: DocScrutinizer on #bash, freenode, said I should use fuser -k -SIGUSR1 /tmp/mumufifo to kill tail instead of getting tail's pid and stuff; I just don't want to also kill perl(in this case grep)

exit 2 #IGNORE BELOW
#exec 3< <( coproc { sleep 20 ; echo "1"; } )
coproc { sleep 20 ; echo "1" >3; }
jobpid="$COPROC_PID"
if test -z "$COPROC_PID"; then
  echo "empty"
  exit 1
fi

echo "jobpid: $jobpid"
ps "$jobpid"
#pgrep -P $COPROC_PID
grep --color=always "1" <&3
