#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash
export RUST_BACKTRACE=1
cargo clean
cargo run
cargo expand
rust-analyzer diagnostics .
echo "exit code: $?"
