#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash

export RUST_BACKTRACE=1
cargo clean
#cargo run --target=x86_64-pc-linux-gnu #bad, doesn't exist in rustc --print target-list
cargo run --target=x86_64-unknown-linux-gnu
echo "exit code: $?"
#sleep 2
