#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash
set -e
cargo clean
RUSTC="$(realpath ./myrust)"
export RUSTC
set +e
export RUST_BACKTRACE=1
cargo run ; ec="$?"
echo "exit code: $ec"
