#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash
cargo clean
export RUSTC="$(realpath ./myrust)"
#export RUST_BACKTRACE=1
cargo run ; ec="$?"
echo "exit code: $ec"
