#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash

export RUST_BACKTRACE=1
rust-analyzer --version
rust-analyzer diagnostics ./
echo "exit code: $?"
