[package]
name = "built"
version = "0.2.3"
description = "Provides a crate with information from the time it was built."
repository = "https://github.com/lukaslueg/built"
documentation = "https://docs.rs/built"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["cargo", "build"]

[badges]
travis-ci = { repository = "lukaslueg/built" }

[features]
default = ["serialized_git", "serialized_time", "serialized_version"]
serialized_git = ["git2"]
serialized_time = ["time"]
serialized_version = ["semver"]

[dependencies]
toml = "0.4"
semver = { version="0.9", optional=true }
time = { version="0.1", optional=true }
git2 = { version="0.6", optional=true, default-features = false, features = [] }

[dev-dependencies]
tempdir = "0.3"
semver = "0.9"
time = "0.1"
git2 = "0.6"
