#!/bin/bash

set -e
set -o nounset
#dir="/var/tmp/portage/dev-lang/rust-1.75.0-r1/work/rustc-1.75.0-src"
dir="/var/tmp/portage/dev-lang/rust-1.76.0-r1/work/rustc-1.76.0-src"
export LD_LIBRARY_PATH="${dir}/build/x86_64-unknown-linux-gnu/stage1/lib:${dir}/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib"
export RUSTC="${dir}/build/x86_64-unknown-linux-gnu/stage1/bin/rustc"

"${dir}/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "$@"
