#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash

libpath="./target/debug/"
libname="forking_test4"
set -ex -o nounset
cargo build
gcc -o my_program src/main.c "-L$libpath" "-l$libname" "-Wl,-rpath,$libpath"
./my_program
