#!/bin/bash
#
#if you're wondering "wait a minute!", this is just because I don't want to associate my new nick(s) or alias, with the old ones!

#XXX: uncomment when needed:
#find . -name "Cargo.toml" -type f -print0 | xargs --replace='{}' --max-args=1 -0 -- sed -e 's/authors = \[ "Your name <you@example.com>" \]/authors = [ "" ]/g' -i {}
find . -name "Cargo.toml" -type f -print0 | xargs --replace='{}' --max-args=1 -0 -- sed -e 's/authors = \[ "Your name <you@example\.com>" \]/authors = [ "xftroxgpx <xftroxgpx@protonmail.com>" ]/g' -i {}

#XXX: ignore:
#the following will break if any spaces in paths/names
#for i in `find . -name Cargo.toml`; do
# echo $i
#done

