#!/bin/bash
#^ syntax highlighting

echo execute ./go from vim by typing:   :!./go
#unset RUST_BACKTRACE #workaround issue: 29293 https://github.com/rust-lang/rust/issues/29293
#or else it will hang on each file write (when rust.vim and syntactic!)

fil="./src/bin/main.rs"
if ! test -e "$fil"; then
  fil="./src/lib.rs"
fi
time vim -- "$fil" && rustfmt -- "$fil"
