#!/usr/bin/env -S PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:${PATH}" bash

export RUST_BACKTRACE=1
cargo clean
#last one overrides:
tlsmodel="global-dynamic"
tlsmodel="local-dynamic"
tlsmodel="emulated"
tlsmodel="local-exec"
tlsmodel="initial-exec"
RUSTFLAGS="-Z tls-model=${tlsmodel}" cargo run
echo "exit code: $?"
